//! Phase 4 (NSS) — `PressurePredictor` trait scaffolding.
//!
//! ## What this file is for
//!
//! Phase 4 of the CANA roadmap integrates the **Neural Systems Simulator
//! (NSS)** — a deterministic, SSM-based architecture from a sibling fork —
//! with CANA's compile-time recommendation engine. NSS predicts *runtime
//! pressure* (CPU / Memory / Thermal / Throughput) across a topology of
//! nodes; Phase 4 maps that substrate onto CANA's per-function MIR view
//! and feeds the predictions back into the cost model.
//!
//! **NSS is NOT yet in this workspace.** When it lands (target: as
//! `crates/cjc-nss`), Phase 4 needs:
//!
//!   1. A bridge crate `crates/cjc-cana-nss` that implements this trait
//!      against `cjc_nss::ClusterNeuralSystemsSimulator`.
//!   2. A [`crate::thermal_cost_model::ThermalAwareCostModel`] wrapper
//!      that composes a base `CostModel` with a `PressurePredictor`.
//!
//! This file ships the trait surface NOW so:
//!
//!   * The bridge crate's authors don't have to invent the surface.
//!   * `ThermalAwareCostModel` is testable today against
//!     [`NullPressurePredictor`].
//!   * Downstream callers (`PassRanker`, `RankingReport`) can take a
//!     `Box<dyn PressurePredictor>` and start type-checking the wiring
//!     before NSS arrives.
//!
//! See `docs/cana/CANA_PHASE_4_NSS_INTEGRATION_DESIGN.md` §3.1 for the
//! full design rationale.

use std::collections::BTreeMap;

use cjc_mir::MirProgram;

use crate::features::CanaFeatures;

// ---------------------------------------------------------------------------
// The trait
// ---------------------------------------------------------------------------

/// A predictor that uses runtime pressure dynamics to inform compile-time
/// decisions.
///
/// Phase 4 implementations wrap NSS to expose its predictions in the
/// vocabulary CANA's other components use. Each method returns a per-function
/// `BTreeMap<String, f64>` keyed by `MirFunction::name`, with values in
/// `[0.0, 1.0]` representing normalized pressure (where 1.0 ≈ "at limit").
///
/// ## Determinism contract
///
/// For a given `(program, features, model_seed)`, every method must produce
/// byte-identical output across runs and platforms. NSS's underlying
/// architecture already guarantees this — see the NSS Phase-1 contract.
/// Stub implementations (like [`NullPressurePredictor`]) trivially satisfy
/// it by returning constants.
///
/// ## Why `BTreeMap` instead of `HashMap`
///
/// CANA's standard determinism rule: ordered iteration. Callers who fold or
/// hash these maps must see the same key order across runs.
pub trait PressurePredictor: std::fmt::Debug {
    /// Predict the per-function thermal pressure under sustained execution.
    ///
    /// Values close to 1.0 ≈ "thermal trip imminent." Callers may use this
    /// to penalize aggressive optimizations on already-hot functions.
    fn predict_thermal(
        &self,
        program: &MirProgram,
        features: &CanaFeatures,
    ) -> BTreeMap<String, f64>;

    /// Predict the per-function peak memory pressure.
    ///
    /// Values close to 1.0 ≈ "OOM risk." Callers may use this to deprioritize
    /// passes that increase working-set size (e.g. function inlining).
    fn predict_memory_peak(
        &self,
        program: &MirProgram,
        features: &CanaFeatures,
    ) -> BTreeMap<String, f64>;

    /// Predict the per-function CPU saturation under sustained execution.
    ///
    /// Values close to 1.0 ≈ "single core pegged." Useful for deciding
    /// whether parallelization passes would help or hurt.
    fn predict_cpu_saturation(
        &self,
        program: &MirProgram,
        features: &CanaFeatures,
    ) -> BTreeMap<String, f64>;

    /// Identify "structural" hot kernels — functions whose pressure
    /// trajectory persists at the longest NSS timescale (α=0.99).
    ///
    /// These are the canonical Phase 3 fusion / Phase 6 native-lowering
    /// targets: code paths that aren't transient blips but durable hot
    /// spots that justify aggressive specialization.
    fn identify_structural_hot_kernels(
        &self,
        program: &MirProgram,
        features: &CanaFeatures,
    ) -> Vec<String>;

    /// Model name + version for audit reports.
    ///
    /// Conventions:
    ///   - `"null"` — [`NullPressurePredictor`]
    ///   - `"nss_v1"` — Phase 4 bridge using NSS Phase-1 cluster predictor
    fn name(&self) -> &'static str;

    /// Model version number, monotonically increasing. Persisted in
    /// `CanaReport` so a future re-analysis can detect when predictions
    /// were generated by an older model.
    fn version(&self) -> u32;
}

// ---------------------------------------------------------------------------
// The null implementation — usable today
// ---------------------------------------------------------------------------

/// A no-op predictor that returns 0.0 for every function on every axis.
///
/// Use cases:
///   - **Default**: programs analyzed by Phase 1-3 (pre-NSS) get this
///     implicitly when callers don't inject a real predictor.
///   - **Tests**: [`crate::thermal_cost_model::ThermalAwareCostModel`]
///     unit tests use this so they're decoupled from NSS landing.
///   - **Audit baseline**: comparing a real NSS predictor's output to
///     this baseline reveals which functions the model actually flags.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct NullPressurePredictor;

impl PressurePredictor for NullPressurePredictor {
    fn predict_thermal(
        &self,
        program: &MirProgram,
        _features: &CanaFeatures,
    ) -> BTreeMap<String, f64> {
        all_fns_zero(program)
    }

    fn predict_memory_peak(
        &self,
        program: &MirProgram,
        _features: &CanaFeatures,
    ) -> BTreeMap<String, f64> {
        all_fns_zero(program)
    }

    fn predict_cpu_saturation(
        &self,
        program: &MirProgram,
        _features: &CanaFeatures,
    ) -> BTreeMap<String, f64> {
        all_fns_zero(program)
    }

    fn identify_structural_hot_kernels(
        &self,
        _program: &MirProgram,
        _features: &CanaFeatures,
    ) -> Vec<String> {
        Vec::new()
    }

    fn name(&self) -> &'static str {
        "null"
    }

    fn version(&self) -> u32 {
        0
    }
}

/// Build a `function_name → 0.0` map for every function in the program.
/// Used by every `NullPressurePredictor` axis.
fn all_fns_zero(program: &MirProgram) -> BTreeMap<String, f64> {
    program
        .functions
        .iter()
        .map(|f| (f.name.clone(), 0.0))
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::features::extract;
    use cjc_mir::{MirBody, MirFnId, MirFunction};

    fn empty_fn(name: &str) -> MirFunction {
        MirFunction {
            id: MirFnId(0),
            name: name.to_string(),
            type_params: vec![],
            params: vec![],
            return_type: None,
            body: MirBody {
                stmts: vec![],
                result: None,
            },
            is_nogc: false,
            cfg_body: None,
            decorators: vec![],
            vis: cjc_ast::Visibility::Public,
            local_count: 0,
        }
    }

    fn make_program(fn_names: &[&str]) -> MirProgram {
        MirProgram {
            functions: fn_names.iter().map(|n| empty_fn(n)).collect(),
            struct_defs: vec![],
            enum_defs: vec![],
            entry: MirFnId(0),
        }
    }

    #[test]
    fn null_predictor_thermal_is_zero_everywhere() {
        let p = make_program(&["a", "b", "c"]);
        let f = extract(&p);
        let pp = NullPressurePredictor;
        let t = pp.predict_thermal(&p, &f);
        assert_eq!(t.len(), 3);
        for v in t.values() {
            assert_eq!(*v, 0.0);
        }
    }

    #[test]
    fn null_predictor_memory_is_zero_everywhere() {
        let p = make_program(&["a", "b"]);
        let f = extract(&p);
        let pp = NullPressurePredictor;
        let m = pp.predict_memory_peak(&p, &f);
        assert!(m.values().all(|&v| v == 0.0));
    }

    #[test]
    fn null_predictor_cpu_is_zero_everywhere() {
        let p = make_program(&["main"]);
        let f = extract(&p);
        let pp = NullPressurePredictor;
        let c = pp.predict_cpu_saturation(&p, &f);
        assert_eq!(c.get("main"), Some(&0.0));
    }

    #[test]
    fn null_predictor_finds_no_hot_kernels() {
        let p = make_program(&["a", "b"]);
        let f = extract(&p);
        let pp = NullPressurePredictor;
        let hot = pp.identify_structural_hot_kernels(&p, &f);
        assert!(hot.is_empty());
    }

    #[test]
    fn null_predictor_identifies_itself_correctly() {
        let pp = NullPressurePredictor;
        assert_eq!(pp.name(), "null");
        assert_eq!(pp.version(), 0);
    }

    #[test]
    fn null_predictor_output_is_deterministic() {
        let p = make_program(&["a", "b", "c"]);
        let f = extract(&p);
        let pp = NullPressurePredictor;
        let first = pp.predict_thermal(&p, &f);
        for _ in 0..50 {
            let again = pp.predict_thermal(&p, &f);
            assert_eq!(first, again);
        }
    }

    #[test]
    fn null_predictor_map_uses_btreemap_ordering() {
        // Insert programs out-of-alphabetical-order; predictor returns
        // them in BTreeMap-sorted order regardless.
        let p = make_program(&["zebra", "alpha", "middle"]);
        let f = extract(&p);
        let pp = NullPressurePredictor;
        let t = pp.predict_thermal(&p, &f);
        let keys: Vec<&str> = t.keys().map(|s| s.as_str()).collect();
        assert_eq!(keys, vec!["alpha", "middle", "zebra"]);
    }
}
