"""Render REPORT.md from a run directory's JSONL results.

    python report.py <run_dir> [--title "..."]

Reads results.jsonl (CJC), results_aer.jsonl, results_stim.jsonl. Every table
cell is a median over the recorded repetitions, and the case_id column links
each row to its JSONL records. Cells with status skipped_size / error are
shown as such, never dropped (BENCHMARK_PLAN §7).
"""
import json
import os
import sys
from collections import OrderedDict


def load(path):
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        return [json.loads(l) for l in f if l.strip()]


def fmt_t(r):
    if r is None:
        return "—"
    if r["status"] != "ok":
        return f"*{r['status']}*"
    t = r["timing"]["median_s"]
    if t is None:
        return "—"
    return f"{t*1e3:.2f} ms" if t < 1 else f"{t:.2f} s"


def fmt_phase(r, phase):
    if r is None:
        return "—"
    if r["status"] != "ok":
        return f"*{r['status']}*"
    t = (r["timing"].get("phases_median_s") or {}).get(phase)
    if t is None:
        return "—"
    return f"{t*1e3:.2f} ms" if t < 1 else f"{t:.2f} s"


def fmt_e(x):
    return "—" if x is None else f"{x:.1e}"


def fmt_mem(r):
    b = r and r["memory"]["peak_rss_bytes"]
    return "—" if not b else f"{b/2**20:.0f} MiB"


def main():
    run_dir = sys.argv[1]
    title = sys.argv[sys.argv.index("--title") + 1] if "--title" in sys.argv else "CJC quantum benchmark"
    cjc = load(os.path.join(run_dir, "results.jsonl"))
    ext = load(os.path.join(run_dir, "results_aer.jsonl")) + load(os.path.join(run_dir, "results_stim.jsonl"))
    by = OrderedDict()
    for r in cjc + ext:
        by.setdefault(r["case_id"], {})[(r["simulator"]["name"], r["simulator"]["path"])] = r

    first = cjc[0] if cjc else {}
    m = first.get("machine", {})
    tc = first.get("toolchain", {})
    sim = first.get("simulator", {})
    aer = next((r["simulator"] for r in ext if r["simulator"]["name"] == "qiskit-aer"), None)
    stm = next((r["simulator"] for r in ext if r["simulator"]["name"] == "stim"), None)
    L = [f"# {title}", ""]
    L += ["Generated by `bench/quantum_compare/report.py` from the JSONL files in this directory.",
          "Times are medians of the recorded repetitions (after one warm-up); see each record for",
          "`reps`, IQR, and phase split. CJC threads only its gate kernels and only above 2^15",
          "amplitude pairs per thread (`runtime_policy` thread count); results are identical at",
          "any thread count.", "",
          "**Which column to compare.** For dense cases the *execute* columns are the simulator",
          "comparison: circuit in, statevector out. *Total* adds build (QASM parse) and observe",
          "(probabilities + 1,000 shots on the Rust and Aer paths; `q_probs` only in the eval / mir",
          "programs, except W6). For MPS cases Aer computes ⟨Z_i⟩ inside `run()`, so only totals",
          "are comparable.", ""]
    L += ["| | |", "|---|---|",
          f"| Machine | {m.get('cpu')} · {m.get('threads')} hardware threads · {m.get('os')} |",
          f"| CJC | cjc-quantum {sim.get('version')} @ `{sim.get('git_sha')}` (dirty: {sim.get('dirty')}), {tc.get('rustc')}, release |",
          f"| Qiskit Aer | {aer and aer.get('version')} (qiskit {aer and aer.get('qiskit')}) |",
          f"| Stim | {stm and stm.get('version')} |", ""]

    def section(title, pred, cols, extra, execute=()):
        rows = [(cid, recs) for cid, recs in by.items() if pred(cid, recs)]
        if not rows:
            return
        L.append(f"## {title}")
        L.append("")
        tot = " total" if execute else ""
        head = (["case_id"] + [c[0] + " execute" for c in execute] + [c[0] + tot for c in cols]
                + [e[0] for e in extra])
        L.append("| " + " | ".join(head) + " |")
        L.append("|" + "---|" * len(head))
        for cid, recs in rows:
            cells = ([f"`{cid}`"] + [fmt_phase(recs.get(c[1]), "execute") for c in execute]
                     + [fmt_t(recs.get(c[1])) for c in cols] + [e[1](recs) for e in extra])
            L.append("| " + " | ".join(cells) + " |")
        L.append("")

    CJC = [("CJC rust", ("cjc-quantum", "rust")), ("CJC eval", ("cjc-quantum", "eval")),
           ("CJC mir", ("cjc-quantum", "mir"))]
    AER = [("Aer 1-thread", ("qiskit-aer", "aer-1t-nofusion")), ("Aer default", ("qiskit-aer", "aer-default"))]

    def rust(recs):
        return recs.get(("cjc-quantum", "rust"))

    def det(recs):
        r = rust(recs)
        if r is None:
            return "—"
        d = r["determinism"]
        return f"replay {'✓' if d['replay_ok'] else '✗'} · paths {'✓' if d['cross_executor_ok'] else ('—' if d['cross_executor_ok'] is None else '✗')}"

    def aer_acc(recs):
        a = recs.get(("qiskit-aer", "aer-1t-nofusion"))
        if not a:
            return "—"
        f = a["accuracy"].get("fidelity")
        s = f"L∞ {fmt_e(a['accuracy']['linf'])}"
        return s + (f", |1−F| {fmt_e(abs(1 - f))}" if f is not None else "") + f" ({a['accuracy']['oracle']})"

    def cjc_oracle(recs):
        r = rust(recs)
        if not r or r["accuracy"]["oracle"] is None:
            return "—"
        return f"{r['accuracy']['oracle']}: {fmt_e(r['accuracy']['linf'])}"

    def stim_acc(recs):
        s = recs.get(("stim", "stim-tableau"))
        if not s:
            return "—"
        a = s.get("agreement", {})
        return (f"peek_z mismatches {a.get('peek_z_mismatches')}/{a.get('n')}; "
                f"forced outcomes {a.get('record_forced_outcomes')}, mismatches {a.get('record_forced_mismatches')}")

    def mem(recs):
        return fmt_mem(rust(recs))

    EXEC = [CJC[0]] + AER
    section("W1 — GHZ, dense statevector (probabilities + 1,000 shots)",
            lambda c, r: c.startswith("W1_"), CJC + AER,
            [("CJC oracle", cjc_oracle), ("CJC vs Aer", aer_acc), ("CJC determinism", det), ("CJC peak mem", mem)],
            EXEC)
    section("W2 — random circuits, dense statevector",
            lambda c, r: c.startswith("W2_"), CJC + AER,
            [("CJC vs Aer", aer_acc), ("CJC determinism", det), ("CJC peak mem", mem)], EXEC)
    section("W6 — one circuit observed three times (`q_probs`, `q_sample`, `q_measure`)",
            lambda c, r: c.startswith("W6_"), CJC + AER,
            [("CJC vs Aer", aer_acc), ("CJC determinism", det), ("CJC peak mem", mem)], EXEC)
    section("W3 — random Clifford, stabilizer",
            lambda c, r: c.startswith("W3_"),
            CJC + [("Stim tableau", ("stim", "stim-tableau")), ("Stim bulk 1k shots†", ("stim", "stim-compile_sampler"))],
            [("CJC vs Stim (exact)", stim_acc), ("CJC determinism", det), ("CJC peak mem", mem)])
    section("W4 — MPS (⟨Z_i⟩ on every qubit)",
            lambda c, r: c.startswith("W4"), CJC + AER,
            [("CJC oracle", cjc_oracle), ("CJC vs Aer", aer_acc), ("CJC determinism", det), ("CJC peak mem", mem)])

    L += ["† Stim's compiled bulk sampler has no CJC counterpart; shown for context only.", "",
          "**Reading the columns.** *CJC rust* is the direct library API (QASM import → execute →",
          "observe). *CJC eval / mir* run the generated `.cjcl` program in each executor, so they",
          "include parsing and interpreter dispatch. *paths ✓* means all CJC paths produced",
          "byte-identical output; *replay ✓* means a fresh process reproduced the SHA-256.", ""]
    with open(os.path.join(run_dir, "REPORT.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(L))
    print("wrote", os.path.join(run_dir, "REPORT.md"))


if __name__ == "__main__":
    main()
