// OpenQASM 2.0 import/export (`q_to_qasm`, `q_from_qasm`).
//
// - Qiskit-authored fixtures: QASM written by qiskit.qasm2.dumps and the
//   statevector Qiskit Aer computes for it (fixtures/qasm, generated by
//   bench/quantum_compare/externals/make_qasm_fixtures.py). CJC must import the
//   text and reproduce Aer's amplitudes.
// - Round trips are exact (bit-identical amplitudes), on both backends and in
//   both executors.
// - Malformed input is an error, never a panic.

use std::rc::Rc;

use cjc_quantum::dispatch_quantum;
use cjc_runtime::value::Value;

fn call(name: &str, args: &[Value]) -> Value {
    dispatch_quantum(name, args)
        .unwrap_or_else(|e| panic!("{name} failed: {e}"))
        .unwrap_or_else(|| panic!("{name} not handled"))
}

fn s(x: &str) -> Value {
    Value::String(Rc::new(x.to_string()))
}

fn amplitudes(c: &Value) -> Vec<(f64, f64)> {
    match call("q_amplitudes", &[c.clone()]) {
        Value::Array(a) => a
            .iter()
            .map(|v| match v {
                Value::Complex(z) => (z.re, z.im),
                other => panic!("expected Complex, got {other}"),
            })
            .collect(),
        other => panic!("expected array, got {other}"),
    }
}

fn fixture(name: &str) -> (String, Vec<(f64, f64)>) {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/beta_tests/quantum/fixtures/qasm/");
    let qasm = std::fs::read_to_string(format!("{dir}{name}.qasm")).expect("fixture qasm");
    let bytes = std::fs::read(format!("{dir}{name}.aer_c128le.bin")).expect("fixture amplitudes");
    let amps = bytes
        .chunks_exact(16)
        .map(|c| {
            (
                f64::from_le_bytes(c[..8].try_into().unwrap()),
                f64::from_le_bytes(c[8..].try_into().unwrap()),
            )
        })
        .collect();
    (qasm, amps)
}

#[test]
fn qasm_fixtures_match_qiskit_aer() {
    for name in ["bell", "every_gate", "two_registers", "random_8q_d6"] {
        let (qasm, aer) = fixture(name);
        for backend in [None, Some("pure")] {
            let c = match backend {
                Some(b) => call("q_from_qasm", &[s(&qasm), s(b)]),
                None => call("q_from_qasm", &[s(&qasm)]),
            };
            let cjc = amplitudes(&c);
            assert_eq!(cjc.len(), aer.len(), "{name}");
            let linf = cjc
                .iter()
                .zip(&aer)
                .map(|(a, b)| (a.0 - b.0).abs().max((a.1 - b.1).abs()))
                .fold(0.0, f64::max);
            assert!(linf < 1e-12, "{name} ({backend:?}): L-inf vs Aer = {linf:e}");
        }
    }
}

#[test]
fn export_then_import_is_bit_identical() {
    let mut c = call("qubits", &[Value::Int(3)]);
    for (g, args) in [
        ("q_h", vec![Value::Int(0)]),
        ("q_rx", vec![Value::Int(1), Value::Float(0.123456789)]),
        ("q_ry", vec![Value::Int(2), Value::Float(-2.5e-9)]),
        ("q_rz", vec![Value::Int(0), Value::Float(1234.5)]),
        ("q_cx", vec![Value::Int(0), Value::Int(2)]),
        ("q_toffoli", vec![Value::Int(0), Value::Int(1), Value::Int(2)]),
        ("q_t", vec![Value::Int(1)]),
    ] {
        let mut a = vec![c];
        a.extend(args);
        c = call(g, &a);
    }
    let text = call("q_to_qasm", &[c.clone()]);
    let back = call("q_from_qasm", &[text.clone()]);
    let (x, y) = (amplitudes(&c), amplitudes(&back));
    for (a, b) in x.iter().zip(&y) {
        assert_eq!((a.0.to_bits(), a.1.to_bits()), (b.0.to_bits(), b.1.to_bits()));
    }
    // Exporting again gives the same text.
    assert_eq!(text.to_string(), call("q_to_qasm", &[back]).to_string());
}

#[test]
fn random_circuits_round_trip_exactly() {
    // Seeded sweep over random gate sequences (all 13 gate kinds).
    let mut seed = 0x51A5_u64;
    let mut next = || {
        seed = seed.wrapping_add(0x9e3779b97f4a7c15);
        let mut z = seed;
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58476d1ce4e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d049bb133111eb);
        z ^ (z >> 31)
    };
    for _ in 0..200 {
        let n = 3 + (next() % 3) as i64;
        let mut c = call("qubits", &[Value::Int(n)]);
        for _ in 0..(next() % 20) {
            let q = |r: u64| Value::Int((r % n as u64) as i64);
            let (a, b, t) = (next() % n as u64, next(), next());
            let b = (a + 1 + b % (n as u64 - 1)) % n as u64;
            let t2 = (0..n as u64).find(|x| *x != a && *x != b).unwrap();
            let angle = Value::Float(f64::from_bits(t) % 100.0);
            let angle = match angle {
                Value::Float(x) if x.is_finite() => Value::Float(x),
                _ => Value::Float(0.5),
            };
            let (name, args): (&str, Vec<Value>) = match next() % 13 {
                0 => ("q_h", vec![q(a)]),
                1 => ("q_x", vec![q(a)]),
                2 => ("q_y", vec![q(a)]),
                3 => ("q_z", vec![q(a)]),
                4 => ("q_s", vec![q(a)]),
                5 => ("q_t", vec![q(a)]),
                6 => ("q_rx", vec![q(a), angle]),
                7 => ("q_ry", vec![q(a), angle]),
                8 => ("q_rz", vec![q(a), angle]),
                9 => ("q_cx", vec![q(a), q(b)]),
                10 => ("q_cz", vec![q(a), q(b)]),
                11 => ("q_swap", vec![q(a), q(b)]),
                _ => ("q_toffoli", vec![q(a), q(b), q(t2)]),
            };
            let mut all = vec![c];
            all.extend(args);
            c = call(name, &all);
        }
        let text = call("q_to_qasm", &[c.clone()]);
        let back = call("q_from_qasm", &[text.clone()]);
        assert_eq!(text.to_string(), call("q_to_qasm", &[back.clone()]).to_string());
        for (x, y) in amplitudes(&c).iter().zip(&amplitudes(&back)) {
            assert_eq!((x.0.to_bits(), x.1.to_bits()), (y.0.to_bits(), y.1.to_bits()));
        }
    }
}

#[test]
fn pure_backend_export_matches_default_backend() {
    let (qasm, _) = fixture("every_gate");
    let a = call("q_to_qasm", &[call("q_from_qasm", &[s(&qasm)])]).to_string();
    let b = call("q_to_qasm", &[call("q_from_qasm", &[s(&qasm), s("pure")])]).to_string();
    assert_eq!(a, b);
}

#[test]
fn qasm_builtins_agree_in_both_executors() {
    let src = r#"
        fn main() -> Any {
            let text = "OPENQASM 2.0;\ninclude \"qelib1.inc\";\nqreg q[2];\nh q[0];\ncx q[0],q[1];\nrz(pi/4) q[1];\n";
            let c = q_from_qasm(text);
            c = q_ry(c, 0, 0.3);
            let back = q_from_qasm(q_to_qasm(c));
            [q_probs(back), q_n_gates(back)]
        }
    "#;
    let (program, diags) = cjc_parser::parse_source(src);
    assert!(!diags.has_errors());
    let a = cjc_eval::Interpreter::new(1).exec(&program).expect("eval");
    let (b, _) = cjc_mir_exec::run_program_with_executor(&program, 1).expect("mir");
    assert_eq!(a.to_string(), b.to_string());
    assert!(a.to_string().ends_with(", 4]"), "{}", a);
}

#[test]
fn malformed_qasm_is_an_error_not_a_panic() {
    let bad = [
        "",
        "garbage",
        "OPENQASM 2.0;",
        "OPENQASM 2.0; qreg q[2]; h q[5];",
        "OPENQASM 2.0; qreg q[2]; u3(1,2,3) q[0];",
        "OPENQASM 2.0; qreg q[2]; rx((((1) q[0];",
        "OPENQASM 2.0; qreg q[99999999999999999999];",
        "OPENQASM 2.0; qreg q[2]; cx q[0], q[0];",
        "OPENQASM 2.0; qreg q[2]; h q[0]]];",
        "OPENQASM 2.0; qreg q[2]; rx(pi**2) q[0];",
        "\u{0}\u{1}OPENQASM",
    ];
    for text in bad {
        let r = std::panic::catch_unwind(|| dispatch_quantum("q_from_qasm", &[s(text)]));
        match r {
            Ok(Err(_)) => {}
            other => panic!("{text:?}: expected Err, got {:?}", other.map(|r| r.map(|v| v.map(|v| v.to_string())))),
        }
    }
    assert!(dispatch_quantum("q_from_qasm", &[Value::Int(1)]).is_err());
    assert!(dispatch_quantum("q_from_qasm", &[s("OPENQASM 2.0; qreg q[1];"), s("fast")]).is_err());
    assert!(dispatch_quantum("q_to_qasm", &[call("mps_new", &[Value::Int(2), Value::Int(2)])]).is_err());
}
